In [3]:
import pandas as pd

In [5]:
df = pd.read_csv('/Users/phayate/src/HRAna.prvt/Result/analyze-deta.csv', index_col=0,header=0)

In [8]:
df

     rank  pred      urid       race_id  rank.1           rid
0       1     9   2030405  201302030405       1  201610020810
1       1     3   2040102  201302040102       1  201610020810
2       1     3   2040601  201302040601       1  201610020810
3       1     5   8040201  201308040201       1  201610020810
4       1     3   8040703  201308040703       1  201610020810
5       1     9   7040205  201307040205       1  201610020810
6       1    10   8010805  201408010805       1  201610020810
7       1     9   8020506  201408020506       1  201610020810
8       1     3   9010105  201409010105       1  201610020810
9       1     9   9010805  201409010805       1  201610020810
10      1     9   9020506  201409020506       1  201610020810
11      1     9   8030511  201408030511       1  201610020810
12      1     9   8031205  201408031205       1  201610020810
13      1     9   3020211  201403020211       1  201610020810
14      1     9   1010711  201401010711       1  201610020810
15      1     8   1020311  201401020311       1  201610020810
16      1     9   5050809  201405050809       1  201610020810
17      1     7   8010510  201508010510       1  201610020810
18      1     9   9010709  201509010709       1  201610020810
19      1    10   9020710  201509020710       1  201610020810
20      1     2   8030912  201508030912       1  201610020810
21      1    11   9030808  201509030808       1  201610020810
22      1     1   1010310  201501010310       1  201610020810
23      1     9   1020408  201501020408       1  201610020810
24      1     3   9040408  201509040408       1  201610020810
25      1     2   9040907  201509040907       1  201610020810
26      1     2   3030112  201503030112       1  201610020810
27      1     9   9050409  201509050409       1  201610020810
28      1     4   8010112  201608010112       1  201610020810
29      1     9   9010709  201609010709       1  201610020810
..    ...   ...       ...           ...     ...           ...
210     9     2   4010808  201504010808       9  201610020810
211     9     9   8031207  201508031207       9  201610020810
212     9     7  10020409  201510020409       9  201610020810
213     9     9  10020908  201510020908       9  201610020810
214     9     2  10021209  201510021209       9  201610020810
215     9     1   3030412  201503030412       9  201610020810
216     9     9  10010608  201610010608       9  201610020810
217     9    10   9020710  201609020710       9  201610020810
218     9     2   8030912  201608030912       9  201610020810
219     9     9   5030110  201605030110       9  201610020810
220     9     1  10020110  201610020110       9  201610020810
221    10     1  10020105  201310020105      10  201610020810
222    10     1  10020501  201310020501      10  201610020810
223    10     1  10020909  201310020909      10  201610020810
224    10     1   8050802  201308050802      10  201610020810
225    10     1   9050503  201309050503      10  201610020810
226    10     1   8010305  201408010305      10  201610020810
227    10     1  55021309  201455021309      10  201610020810
228    10     1   9010403  201409010403      10  201610020810
229    10     1   7020605  201407020605      10  201610020810
230    10     1  55072109  201455072109      10  201610020810
231    10     1   3030212  201403030212      10  201610020810
232    10     8   7040312  201407040312      10  201610020810
233    10     1   9010808  201509010808      10  201610020810
234    10     1   9020607  201509020607      10  201610020810
235    10     1   7030410  201507030410      10  201610020810
236    10     1  10020110  201510020110      10  201610020810
237    10     3  10020810  201510020810      10  201610020810
238    10     8   9040109  201509040109      10  201610020810
239    10     1  10020110  201610020110      10  201610020810

[240 rows x 6 columns]

In [22]:
sorted_df = df.sort_values(by=["pred"], ascending=True)

In [12]:
sorted_df

     rank  pred      urid       race_id  rank.1           rid
239    10     1  10020110  201610020110      10  201610020810
197     9     1   8010305  201408010305       9  201610020810
183     8     1   9050105  201409050105       8  201610020810
32      1     1   9030110  201609030110       1  201610020810
179     7     1  10020110  201610020110       7  201610020810
34      1     1  10020110  201610020110       1  201610020810
87      4     1   9050811  201409050811       4  201610020810
141     6     1   3030212  201403030212       6  201610020810
139     6     1  10021009  201410021009       6  201610020810
134     6     1   9050503  201309050503       6  201610020810
131     5     1  10020110  201610020110       5  201610020810
130     5     1   7030410  201607030410       5  201610020810
129     5     1   9030710  201609030710       5  201610020810
125     5     1   8010412  201608010412       5  201610020810
117     5     1   7030110  201407030110       5  201610020810
110     5     1   7030808  201307030808       5  201610020810
65      3     1   7030210  201507030210       3  201610020810
101     4     1   9030710  201609030710       4  201610020810
208     9     1   9010808  201509010808       9  201610020810
22      1     1   1010310  201501010310       1  201610020810
178     7     1   9020112  201609020112       7  201610020810
227    10     1  55021309  201455021309      10  201610020810
236    10     1  10020110  201510020110      10  201610020810
235    10     1   7030410  201507030410      10  201610020810
234    10     1   9020607  201509020607      10  201610020810
233    10     1   9010808  201509010808      10  201610020810
231    10     1   3030212  201403030212      10  201610020810
230    10     1  55072109  201455072109      10  201610020810
229    10     1   7020605  201407020605      10  201610020810
228    10     1   9010403  201409010403      10  201610020810
..    ...   ...       ...           ...     ...           ...
146     6     9   7030209  201507030209       6  201610020810
0       1     9   2030405  201302030405       1  201610020810
138     6     9   4020509  201404020509       6  201610020810
135     6     9   8010503  201408010503       6  201610020810
46      3     9   4020305  201204020305       3  201610020810
136     6     9   8010904  201408010904       6  201610020810
48      3    10   5050807  201205050807       3  201610020810
164     7    10   7040209  201407040209       7  201610020810
126     5    10   8020110  201608020110       5  201610020810
82      4    10   8030806  201408030806       4  201610020810
175     7    10   8040410  201508040410       7  201610020810
6       1    10   8010805  201408010805       1  201610020810
70      3    10   8020110  201608020110       3  201610020810
145     6    10   9030312  201509030312       6  201610020810
152     6    10   8010208  201608010208       6  201610020810
97      4    10   9020710  201609020710       4  201610020810
198     9    10   8010805  201408010805       9  201610020810
30      1    10   9020710  201609020710       1  201610020810
217     9    10   9020710  201609020710       9  201610020810
19      1    10   9020710  201509020710       1  201610020810
181     8    11   8040603  201408040603       8  201610020810
137     6    11   7030512  201407030512       6  201610020810
88      4    11  10010811  201510010811       4  201610020810
37      2    11   9020709  201509020709       2  201610020810
44      2    11   8020510  201608020510       2  201610020810
174     7    11   9040610  201509040610       7  201610020810
21      1    11   9030808  201509030808       1  201610020810
150     6    11   3030512  201503030512       6  201610020810
192     8    11  10010811  201610010811       8  201610020810
108     5    11   9020709  201309020709       5  201610020810

[240 rows x 6 columns]

In [14]:
urid_df = df[['urid']]

In [17]:
urid_df

         urid
0     2030405
1     2040102
2     2040601
3     8040201
4     8040703
5     7040205
6     8010805
7     8020506
8     9010105
9     9010805
10    9020506
11    8030511
12    8031205
13    3020211
14    1010711
15    1020311
16    5050809
17    8010510
18    9010709
19    9020710
20    8030912
21    9030808
22    1010310
23    1020408
24    9040408
25    9040907
26    3030112
27    9050409
28    8010112
29    9010709
..        ...
210   4010808
211   8031207
212  10020409
213  10020908
214  10021209
215   3030412
216  10010608
217   9020710
218   8030912
219   5030110
220  10020110
221  10020105
222  10020501
223  10020909
224   8050802
225   9050503
226   8010305
227  55021309
228   9010403
229   7020605
230  55072109
231   3030212
232   7040312
233   9010808
234   9020607
235   7030410
236  10020110
237  10020810
238   9040109
239  10020110

[240 rows x 1 columns]

In [20]:
li = urid_df.values.tolist()

In [23]:
print(set(li))

TypeError: unhashable type: 'list'

In [25]:
sorted_df = df.sort_values(by=["urid"], ascending=True)
print(sorted_df)

     rank  pred      urid       race_id  rank.1           rid
22      1     1   1010310  201501010310       1  201610020810
162     7     9   1010506  201401010506       7  201610020810
172     7     6   1010608  201501010608       7  201610020810
14      1     9   1010711  201401010711       1  201610020810
180     8     6   1020205  201401020205       8  201610020810
163     7     9   1020306  201401020306       7  201610020810
15      1     8   1020311  201401020311       1  201610020810
23      1     9   1020408  201501020408       1  201610020810
173     7     9   1020609  201501020609       7  201610020810
160     7     9   2020206  201402020206       7  201610020810
161     7     9   2020506  201402020506       7  201610020810
0       1     9   2030405  201302030405       1  201610020810
52      3     9   2030609  201302030609       3  201610020810
1       1     3   2040102  201302040102       1  201610020810
2       1     3   2040601  201302040601       1  201610020810
170     7     9   3010309  201503010309       7  201610020810
13      1     9   3020211  201403020211       1  201610020810
40      2     9   3020211  201503020211       2  201610020810
118     5     2   3020710  201403020710       5  201610020810
26      1     2   3030112  201503030112       1  201610020810
231    10     1   3030212  201403030212      10  201610020810
141     6     1   3030212  201403030212       6  201610020810
84      4     9   3030310  201403030310       4  201610020810
215     9     1   3030412  201503030412       9  201610020810
150     6    11   3030512  201503030512       6  201610020810
153     6     9   4010310  201604010310       6  201610020810
63      3     8   4010311  201504010311       3  201610020810
199     9     8   4010405  201404010405       9  201610020810
171     7     9   4010409  201504010409       7  201610020810
31      1     8   4010611  201604010611       1  201610020810
..    ...   ...       ...           ...     ...           ...
88      4    11  10010811  201510010811       4  201610020810
192     8    11  10010811  201610010811       8  201610020810
221    10     1  10020105  201310020105      10  201610020810
220     9     1  10020110  201610020110       9  201610020810
236    10     1  10020110  201510020110      10  201610020810
239    10     1  10020110  201610020110      10  201610020810
179     7     1  10020110  201610020110       7  201610020810
34      1     1  10020110  201610020110       1  201610020810
131     5     1  10020110  201610020110       5  201610020810
147     6     3  10020209  201510020209       6  201610020810
91      4     2  10020311  201510020311       4  201610020810
212     9     7  10020409  201510020409       9  201610020810
60      3     7  10020409  201410020409       3  201610020810
222    10     1  10020501  201310020501      10  201610020810
103     4     4  10020510  201610020510       4  201610020810
203     9     8  10020606  201410020606       9  201610020810
111     5     2  10020607  201310020607       5  201610020810
148     6     4  10020809  201510020809       6  201610020810
119     5     3  10020810  201410020810       5  201610020810
237    10     3  10020810  201510020810      10  201610020810
204     9     9  10020907  201410020907       9  201610020810
213     9     9  10020908  201510020908       9  201610020810
223    10     1  10020909  201310020909      10  201610020810
139     6     1  10021009  201410021009       6  201610020810
92      4     3  10021110  201510021110       4  201610020810
214     9     2  10021209  201510021209       9  201610020810
149     6     2  10021209  201510021209       6  201610020810
205     9     2  10021209  201410021209       9  201610020810
227    10     1  55021309  201455021309      10  201610020810
230    10     1  55072109  201455072109      10  201610020810

[240 rows x 6 columns]

In [30]:
urid_df = df[['urid']]
li = urid_df.values.tolist()
print(type(li))

<class 'list'>

In [31]:
print(li)

[[2030405], [2040102], [2040601], [8040201], [8040703], [7040205], [8010805], [8020506], [9010105], [9010805], [9020506], [8030511], [8031205], [3020211], [1010711], [1020311], [5050809], [8010510], [9010709], [9020710], [8030912], [9030808], [1010310], [1020408], [9040408], [9040907], [3030112], [9050409], [8010112], [9010709], [9020710], [4010611], [9030110], [5030710], [10020110], [10010605], [7020510], [9020709], [8031211], [9030608], [3020211], [6040511], [8040210], [8010510], [8020510], [9010409], [4020305], [4030611], [5050807], [9050909], [8010309], [8030309], [2030609], [7040109], [7040608], [9020707], [8030508], [8031208], [9030504], [7030501], [10020409], [4021209], [4030509], [4010311], [5030210], [7030210], [4020110], [4020810], [4021110], [7010212], [8020110], [8020509], [4020110], [8040205], [8050104], [8050802], [8010109], [8010609], [8020509], [9010209], [7020510], [6030811], [8030806], [9040807], [3030310], [8050109], [8050609], [9050811], [10010811], [9010810], [9020811], [10020311], [10021110], [9040310], [8040510], [8050609], [9050409], [9020710], [8030609], [8031208], [9030409], [9030710], [7030610], [10020510], [8010706], [8020505], [9010308], [9020111], [9020709], [8030507], [7030808], [10020607], [9040108], [9040907], [8020608], [9010309], [7020610], [7030110], [3020710], [10020810], [9010309], [8040210], [5040909], [8050609], [9050409], [8010412], [8020110], [8020709], [9010309], [9030710], [7030410], [10020110], [5050306], [8050705], [9050503], [8010503], [8010904], [7030512], [4020509], [10021009], [9040407], [3030212], [5050810], [5020608], [8030912], [9030312], [7030209], [10020209], [10020809], [10021209], [3030512], [9050308], [8010208], [4010310], [8030912], [9030409], [8050707], [9050303], [9010705], [8030101], [2020206], [2020506], [1010506], [1020306], [7040209], [7040609], [7010210], [10010212], [10010707], [7020408], [3010309], [4010409], [1010608], [1020609], [9040610], [8040410], [5010509], [9010309], [9020112], [10020110], [1020205], [8040603], [8050103], [9050105], [8010205], [8010605], [9010505], [9020205], [5020311], [4030206], [8010512], [8020309], [10010811], [8030310], [8031011], [5050205], [8050702], [8010305], [8010805], [4010405], [9030206], [9030704], [7030407], [10020606], [10020907], [10021209], [8010512], [10010609], [9010808], [9020808], [4010808], [8031207], [10020409], [10020908], [10021209], [3030412], [10010608], [9020710], [8030912], [5030110], [10020110], [10020105], [10020501], [10020909], [8050802], [9050503], [8010305], [55021309], [9010403], [7020605], [55072109], [3030212], [7040312], [9010808], [9020607], [7030410], [10020110], [10020810], [9040109], [10020110]]

In [33]:
urid_df = df[['urid']]
li = urid_df.tolist()

AttributeError: 'DataFrame' object has no attribute 'tolist'

In [35]:
li = df['urid'].tolist
print(li)

<bound method Series.tolist of 0       2030405
1       2040102
2       2040601
3       8040201
4       8040703
5       7040205
6       8010805
7       8020506
8       9010105
9       9010805
10      9020506
11      8030511
12      8031205
13      3020211
14      1010711
15      1020311
16      5050809
17      8010510
18      9010709
19      9020710
20      8030912
21      9030808
22      1010310
23      1020408
24      9040408
25      9040907
26      3030112
27      9050409
28      8010112
29      9010709
         ...
210     4010808
211     8031207
212    10020409
213    10020908
214    10021209
215     3030412
216    10010608
217     9020710
218     8030912
219     5030110
220    10020110
221    10020105
222    10020501
223    10020909
224     8050802
225     9050503
226     8010305
227    55021309
228     9010403
229     7020605
230    55072109
231     3030212
232     7040312
233     9010808
234     9020607
235     7030410
236    10020110
237    10020810
238     9040109
239    10020110
Name: urid, dtype: int64>

In [37]:
type(li)

method

In [39]:
set(li)

TypeError: 'method' object is not iterable

In [41]:
l = list(df['urid'])

In [43]:
l

[2030405,
 2040102,
 2040601,
 8040201,
 8040703,
 7040205,
 8010805,
 8020506,
 9010105,
 9010805,
 9020506,
 8030511,
 8031205,
 3020211,
 1010711,
 1020311,
 5050809,
 8010510,
 9010709,
 9020710,
 8030912,
 9030808,
 1010310,
 1020408,
 9040408,
 9040907,
 3030112,
 9050409,
 8010112,
 9010709,
 9020710,
 4010611,
 9030110,
 5030710,
 10020110,
 10010605,
 7020510,
 9020709,
 8031211,
 9030608,
 3020211,
 6040511,
 8040210,
 8010510,
 8020510,
 9010409,
 4020305,
 4030611,
 5050807,
 9050909,
 8010309,
 8030309,
 2030609,
 7040109,
 7040608,
 9020707,
 8030508,
 8031208,
 9030504,
 7030501,
 10020409,
 4021209,
 4030509,
 4010311,
 5030210,
 7030210,
 4020110,
 4020810,
 4021110,
 7010212,
 8020110,
 8020509,
 4020110,
 8040205,
 8050104,
 8050802,
 8010109,
 8010609,
 8020509,
 9010209,
 7020510,
 6030811,
 8030806,
 9040807,
 3030310,
 8050109,
 8050609,
 9050811,
 10010811,
 9010810,
 9020811,
 10020311,
 10021110,
 9040310,
 8040510,
 8050609,
 9050409,
 9020710,
 8030609,
 8031208,
 9030409,
 9030710,
 7030610,
 10020510,
 8010706,
 8020505,
 9010308,
 9020111,
 9020709,
 8030507,
 7030808,
 10020607,
 9040108,
 9040907,
 8020608,
 9010309,
 7020610,
 7030110,
 3020710,
 10020810,
 9010309,
 8040210,
 5040909,
 8050609,
 9050409,
 8010412,
 8020110,
 8020709,
 9010309,
 9030710,
 7030410,
 10020110,
 5050306,
 8050705,
 9050503,
 8010503,
 8010904,
 7030512,
 4020509,
 10021009,
 9040407,
 3030212,
 5050810,
 5020608,
 8030912,
 9030312,
 7030209,
 10020209,
 10020809,
 10021209,
 3030512,
 9050308,
 8010208,
 4010310,
 8030912,
 9030409,
 8050707,
 9050303,
 9010705,
 8030101,
 2020206,
 2020506,
 1010506,
 1020306,
 7040209,
 7040609,
 7010210,
 10010212,
 10010707,
 7020408,
 3010309,
 4010409,
 1010608,
 1020609,
 9040610,
 8040410,
 5010509,
 9010309,
 9020112,
 10020110,
 1020205,
 8040603,
 8050103,
 9050105,
 8010205,
 8010605,
 9010505,
 9020205,
 5020311,
 4030206,
 8010512,
 8020309,
 10010811,
 8030310,
 8031011,
 5050205,
 8050702,
 8010305,
 8010805,
 4010405,
 9030206,
 9030704,
 7030407,
 10020606,
 10020907,
 10021209,
 8010512,
 10010609,
 9010808,
 9020808,
 4010808,
 8031207,
 10020409,
 10020908,
 10021209,
 3030412,
 10010608,
 9020710,
 8030912,
 5030110,
 10020110,
 10020105,
 10020501,
 10020909,
 8050802,
 9050503,
 8010305,
 55021309,
 9010403,
 7020605,
 55072109,
 3030212,
 7040312,
 9010808,
 9020607,
 7030410,
 10020110,
 10020810,
 9040109,
 10020110]

In [45]:
a=set(l)

In [49]:
print(len(a))
print(len(df))

196
240